### ISSUE TITLE
Error during annotation

### ISSUE THREAD

**Issue by SunKKai** [jfnavarro/st_pipeline#105]
Hello, while running the pipeline once it reaches the annotation stage I receive this error in the log txt: 

INFO:STPipeline:Starting annotation 2024-10-08 16:16:42.283977
ERROR:STPipeline:Error during annotation. HTSEQ execution failed

In the error file it gives this:
[bam_sort_core] merging from 0 files and 4 in-memory blocks...
Error running the pipeline
<built-in function delete__Pair_long_obj> returned a result with an error set
Host key verification failed.

Would you happen to know why this is happening? Occurs for all instances, even the test files.

**Comment by xieduo7** [comment]
I encounter the same error

**Comment by SunKKai** [comment]
Hello, for me this was a dependency issue with samtools, make sure all dependencies' versions are compatible with each other. Hopefully that fixes it for you! @xieduo7 

Good luck,
Kevin

**Comment by xieduo7** [comment]
Hi @SunKKai , 

Thanks for your reply! I was wondering what version of HTSeq you are using? I am running into another [issue
](https://github.com/jfnavarro/st_pipeline/issues/106).

Thank you very much!

Best,
Duo

**Comment by SunKKai** [comment]
I am using htseq version 2.0.9, python version 3.7.12
