### ISSUE TITLE
Running st pipeline “name 'out_rw' is not defined”

### ISSUE THREAD

**Issue by ZQ1126** [jfnavarro/st_pipeline#99]
Hi,

Thank you very much for your work.

I ran stpipeline with the following code:

st_pipeline_run.py \
  --output-folder $OUTPUT \
  --temp-folder $TMP \
  --umi-start-position 16 \
  --umi-end-position 26 \
  --ids /home/zhangqiang/spatial_trans/$ID \
  --ref-map $MAP \
  --ref-annotation $ANN \
  --expName $EXP \
  --htseq-no-ambiguous \
  --verbose \
  --threads 16 \
  --log-file $OUTPUT/${EXP}_log.txt \
  --star-two-pass-mode \
  --no-clean-up \
  $FW $RV

I get this error message : 

ST Pipeline, parameters loaded
ST Pipeline, logger created
ST Pipeline, sanity check passed. Starting the run.
Error running the pipeline
name 'out_rw' is not defined

Do you know what causes this error? How can I fix it？

Thank you very much for your help!!

Qiang

**Comment by jfnavarro** [comment]
Hi Qiang!

Which version are you using? What is the content of `$FW` and `$RV`?

Best,
Jose

**Comment by ZQ1126** [comment]
I think I have solved this problem. After i checked the log file, i got this messages"STPipeline:Pair reads found with different names". Afetr I changed the name of reads in the fastq1 and fastq2 files to be the same, this error did not occur again.

By the way, I can successfully run stpipeline now， and got the final TSV file. But, when i check the log file again, i found the follow warnings:
WARNING:STPipeline:Taggd has generated error messages during demultiplexing.
b"[E::idx_find_and_load] Could not retrieve index file for '/home/zhangqiang/spatial_trans/03.stpipeline/10t_6/tmp/mapped.bam'

I am not sure whether this warnings will influence the accuracy of final output results. I can sure that the barcode file could be found correctly, as the TSV file include the location informations.

**Comment by ZQ1126** [comment]
Hi，I think I have solved this problem. After i checked the log file, i got this messages"STPipeline:Pair reads found with different names". Afetr I changed the name of reads in the fastq1 and fastq2 files to be the same, this error did not occur again.

By the way, I can successfully run stpipeline now， and got the final TSV file. But, when i check the log file again, i found the follow warnings:
WARNING:STPipeline:Taggd has generated error messages during demultiplexing.
b"[E::idx_find_and_load] Could not retrieve index file for '/home/zhangqiang/spatial_trans/03.stpipeline/10t_6/tmp/mapped.bam'

I am not sure whether this warnings will influence the accuracy of final output results. I can sure that the barcode file could be found correctly, as the TSV file include the location informations.

**Comment by ZQ1126** [comment]
Hi Jose,

Hi，I think I have solved this problem. After i checked the log file, i got this messages"STPipeline:Pair reads found with different names". Afetr I changed the name of reads in the fastq1 and fastq2 files to be the same, this error did not occur again.

By the way, I can successfully run stpipeline now， and got the final TSV file. But, when i check the log file again, i found the follow warnings:
WARNING:STPipeline:Taggd has generated error messages during demultiplexing.
b"[E::idx_find_and_load] Could not retrieve index file for '/home/zhangqiang/st/10t_6/tmp/mapped.bam' [E::idx_find_and_load] Could not retrieve index file for '/home/zhangqiang/st/10t_6/tmp/mapped.bam'\n[E::idx_find_and_load] Could not retrieve index file for '/home/zhangqiang/st/10t_6/tmp/mapped.bam'........

I am not sure whether this warnings will influence the accuracy of final output results. I can sure that the barcode file could be found correctly, as the TSV file include the location informations.

Best wishes!
Qiang

**Comment by jfnavarro** [comment]
Glad that you solved the issue! Yes, you can ignore the warning. It is not causing any harm.

**Comment by q01010101** [comment]
I had this error too. And the reason is I set A wrong out_path. For example, my data is stored in /AAA/extract_data/, and I creat another folder in /AAA/st_pipeline/, Then I mistakenly submit the OUT_PATH parameter /AAA/st_pipeline/, which should be /AAA/.

**Comment by q01010101** [comment]
I had this error too. It seems like I should create a new Script which include st_pipeline_run.py, and run it by calling this new script. I think It might be associated with the environment setting.
